2025-06-17 07:15:56,799 - INFO - üìã Starting Modularized Optuna Pipeline
2025-06-17 07:15:56,799 - INFO - üì¶ Original shape: (15000, 11)
2025-06-17 07:15:56,799 - INFO - üßπ Cleaning dataset (dropping NaNs)
2025-06-17 07:15:56,800 - INFO - üìê Performing train-test split.
2025-06-17 07:15:56,803 - INFO - ‚úÖ After dropna: (14694, 11)
2025-06-17 07:15:56,803 - INFO - üöÄ Starting optimization for: lightgbm
2025-06-17 08:10:11,305 - ERROR - ‚ùå Error optimizing lightgbm: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "/home/lmorenom/BRICENO_MODULARIZED/main.py", line 102, in run_optuna_pipeline
    eval_results = evaluate_model(best_model, X_test, y_test)
  File "/home/lmorenom/BRICENO_MODULARIZED/evaluate.py", line 12, in evaluate_model
    rmse = mean_squared_error(y_test, y_pred, squared=False)
  File "/home/lmorenom/.optuna_workflow/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-17 08:10:11,305 - INFO - üöÄ Starting optimization for: xgboost
2025-06-17 08:16:45,238 - ERROR - ‚ùå Error optimizing xgboost: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "/home/lmorenom/BRICENO_MODULARIZED/main.py", line 102, in run_optuna_pipeline
    eval_results = evaluate_model(best_model, X_test, y_test)
  File "/home/lmorenom/BRICENO_MODULARIZED/evaluate.py", line 12, in evaluate_model
    rmse = mean_squared_error(y_test, y_pred, squared=False)
  File "/home/lmorenom/.optuna_workflow/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-17 08:16:45,238 - INFO - üöÄ Starting optimization for: random_forest
2025-06-17 12:58:32,754 - ERROR - ‚ùå Error optimizing random_forest: got an unexpected keyword argument 'squared'
Traceback (most recent call last):
  File "/home/lmorenom/BRICENO_MODULARIZED/main.py", line 102, in run_optuna_pipeline
    eval_results = evaluate_model(best_model, X_test, y_test)
  File "/home/lmorenom/BRICENO_MODULARIZED/evaluate.py", line 12, in evaluate_model
    rmse = mean_squared_error(y_test, y_pred, squared=False)
  File "/home/lmorenom/.optuna_workflow/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 194, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'squared'
2025-06-17 12:58:32,754 - INFO - üöÄ Starting optimization for: svr
